// app/medications/api/medicationsList.ts

export const medicationsList = [
  { label: 'Amoxicilina', value: 'Amoxicilina' },
  { label: 'Ibuprofeno', value: 'Ibuprofeno' },
  { label: 'Paracetamol', value: 'Paracetamol' },
  { label: 'Sulfato Ferroso', value: 'SulfatoFerroso' },
  { label: 'Cotrimoxazol', value: 'Cotrimoxazol' },
  { label: 'Eritromicina', value: 'Eritromicina' },
  { label: 'Zinco', value: 'Zinco' },
  { label: 'Vitamina A', value: 'VitaminaA' },
  { label: 'Albendazol', value: 'Albendazol' },
  { label: 'Mebendazol', value: 'Mebendazol' },
  { label: 'Ácido Fólico', value: 'AcidoFolico' },
  { label: 'Metronidazol', value: 'Metronidazol' },
  { label: 'Cloroquina Primaquina', value: 'CloroquinaPrimaquina' },
  { label: 'Salbutamol', value: 'Salbutamol' },
  { label: 'Nistatina', value: 'Nistatina' },
  { label: 'Permetrina Benzoato', value: 'PermetrinaBenzoato' },
  { label: 'Cefalexina', value: 'Cefalexina' },
  { label: 'Claritromicina', value: 'Claritromicina' },
  { label: 'Gentamicina (Colírio)', value: 'GentamicinaColirio' },
  { label: 'SRO', value: 'SRO' },
  { label: 'Isotretinoína Tópica', value: 'IsotretinoinaTopica' },
  { label: 'Vitamina D', value: 'VitaminaD' },
  { label: 'Prednisolona', value: 'Prednisolona' },
  { label: 'Aciclovir', value: 'Aciclovir' },
  { label: 'Hidroxizina', value: 'Hidroxizina' },
  { label: 'Bromoprida', value: 'Bromoprida' },
  { label: 'Clorexidina Tópica', value: 'ClorexidinaTopica' },
  { label: 'Tetraciclina (Pomada)', value: 'TetraciclinaPomada' },
  { label: 'Povidona Iodada', value: 'PovidonaIodada' },
  { label: 'Metoclopramida', value: 'Metoclopramida' },
  { label: 'Dexametasona (Oftálmica)', value: 'DexametasonaOftalmica' },
  { label: 'Miconazol', value: 'Miconazol' },
  { label: 'Salicilato de Metila', value: 'SalicilatoDeMetila' },
  { label: 'Corticosteroide Tópico', value: 'CorticosteroideTopico' },
  { label: 'Lidocaína (Gel)', value: 'LidocainaGel' },
  { label: 'Sulfacetamida (Colírio)', value: 'SulfacetamidaColirio' },
  { label: 'Permetrina 1%', value: 'Permetrina1' },
];
