//APP/STYLES/STYLES.TS

import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeAreaView: {
    flex: 1,
    backgroundColor: '#151515',
  },
  container: {
    flexGrow: 1,
    padding: 20,
    backgroundColor: '#151515',
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#A700FF',
    textAlign: 'center',
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 20,
    color: '#A700FF',
    marginBottom: 10,
    fontWeight: 'bold',
  },
  input: {
    width: '100%',
    marginBottom: 15,
    padding: 15,
    backgroundColor: '#363636',
    borderRadius: 10,
    color: '#fff',
    fontSize: 16,
  },
  inputSmall: {
    flex: 1,
    marginBottom: 15,
    padding: 15,
    backgroundColor: '#363636',
    borderRadius: 10,
    color: '#fff',
    fontSize: 16,
    marginHorizontal: 5,
  },
  inputMultiline: {
    width: '100%',
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    color: '#E0E0E0',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#444',
    textAlignVertical: 'top', // Para manter o texto no topo em campos multilinha
  },
  pickerContainer: {
    flex: 1,
    marginBottom: 15,
    backgroundColor: '#363636',
    borderRadius: 10,
    overflow: 'hidden',
  },
  picker: {
    color: '#fff',
    fontSize: 16,
    height: 50,
    paddingHorizontal: 10,
    backgroundColor: '#363636',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  buttonContainer: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  button: {
    flex: 1,
    padding: 15,
    backgroundColor: '#A700FF',
    borderRadius: 10,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#fff',
    marginTop: 10,
  },
  // Adicionando a estilização específica para a tela de cadastro de prontuário
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1E1E1E',
  },
  attendanceContainer: {
    padding: 20,
    backgroundColor: '#282828',
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#444',
  },
  infoContainer: {
    marginBottom: 20,
    padding: 20,
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  detailsContainer: {
    marginBottom: 20,
    padding: 20,
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#444',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#A700FF',
    marginBottom: 15,
  },
  scrollViewContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  buttonDelete: {
    backgroundColor: '#ff5252',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonConsulta: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonVaccine: {
    backgroundColor: '#FF9800',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  detailItem: {
    fontSize: 18,
    color: '#2e7d32',
    marginBottom: 10,
  },
});

export default styles;
